apiVersion: v1
kind: Secret
data:
  username: am9lYmxvZ2dz
  password: TG9uZyBKb2huIFNpbHZlcg==
  something-else: YW55dGhpbmcgZ29lcyBoZXJl
metadata:
  namespace: secrets-sandbox
  name: azure-sa-secret
  annotations:
    kubernetes.io/service-account.name: azure-sa
type: kubernetes.io/service-account-token
---
# this secret is a negative test to show that we can lock down permissions to a specific secret
# e.g. kubectl --as azure-sa auth can-i get secret/other-secret --namespace secrets-sandbox
apiVersion: v1
kind: Secret
data:
  bla: c29tZSB2YWx1ZQ==
metadata:
  namespace: secrets-sandbox
  name: other-secret
  annotations:
    kubernetes.io/service-account.name: azure-sa
type: kubernetes.io/service-account-token