kind: Deployment
apiVersion: apps/v1beta1
metadata:
  namespace: local-docker-registry-test
  labels:
    app: customer-api
  name: myappdeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-api
  strategy: {}
  template:
    metadata:
      labels:
        app: customer-api
    spec:
      containers:
      - image: lyraproj/customer
        imagePullPolicy: Never
        name: customer-api
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"          
        ports:
        - containerPort: 8080
