/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// BlahsGetter has a method to return a BlahInterface.
// A group's client should implement this interface.
type BlahsGetter interface {
	Blahs(namespace string) BlahInterface
}

// BlahInterface has methods to work with Blah resources.
type BlahInterface interface {
	Create(*Blah) (*Blah, error)
	Update(*Blah) (*Blah, error)
	UpdateStatus(*Blah) (*Blah, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*Blah, error)
	List(opts v1.ListOptions) (*BlahList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *Blah, err error)
	BlahExpansion
}

// blahs implements BlahInterface
type blahs struct {
	client rest.Interface
	ns     string
}

// newBlahs returns a Blahs
func newBlahs(c *SamplecontrollerV1alpha1Client, namespace string) *blahs {
	return &blahs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the blah, and returns the corresponding blah object, and an error if there is any.
func (c *blahs) Get(name string, options v1.GetOptions) (result *Blah, err error) {
	result = &Blah{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("blahs").
		Name(name).
		VersionedParams(&options, ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Blahs that match those selectors.
func (c *blahs) List(opts v1.ListOptions) (result *BlahList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &BlahList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("blahs").
		VersionedParams(&opts, ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested blahs.
func (c *blahs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("blahs").
		VersionedParams(&opts, ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a blah and creates it.  Returns the server's representation of the blah, and an error, if there is any.
func (c *blahs) Create(blah *Blah) (result *Blah, err error) {
	result = &Blah{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("blahs").
		Body(blah).
		Do().
		Into(result)
	return
}

// Update takes the representation of a blah and updates it. Returns the server's representation of the blah, and an error, if there is any.
func (c *blahs) Update(blah *Blah) (result *Blah, err error) {
	result = &Blah{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("blahs").
		Name(blah.Name).
		Body(blah).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *blahs) UpdateStatus(blah *Blah) (result *Blah, err error) {
	result = &Blah{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("blahs").
		Name(blah.Name).
		SubResource("status").
		Body(blah).
		Do().
		Into(result)
	return
}

// Delete takes name of the blah and deletes it. Returns an error if one occurs.
func (c *blahs) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("blahs").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *blahs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("blahs").
		VersionedParams(&listOptions, ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched blah.
func (c *blahs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *Blah, err error) {
	result = &Blah{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("blahs").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
