/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import ()

// Interface provides access to all the informers in this group version.
type Interface interface {
	// Blahs returns a BlahInformer.
	Blahs() BlahInformer
}

type version struct {
	factory          SharedInformerFactory
	namespace        string
	tweakListOptions TweakListOptionsFunc
}

// New returns a new Interface.
func New2(f SharedInformerFactory, namespace string, tweakListOptions TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// Blahs returns a BlahInformer.
func (v *version) Blahs() BlahInformer {
	return &blahInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
