apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: webservers.lyra.example.com
  namespace: crd-stuff
spec:
  group: lyra.example.com
  names:
    kind: WebServer
    listKind: WebServerList
    plural: webservers
    singular: webserver
    shortNames:
    - wf
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      required: ["spec"]
      properties:
        spec:
          required: ["WebServerName"]
          properties:
            WebServerName:
              type: "string"
            WebServerId:
              type: "string"
            refreshTime:
              type: "integer"
              minimum: 30
              maximum: 6000